//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int TableNo { get; set; }
        public string OrderId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderTime { get; set; }
        public int OrderIndex { get; set; }
        public Nullable<int> BillID { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
