//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public string MenuId { get; set; }
        public long Quantity { get; set; }
        public decimal OverallPrice { get; set; }
        public int Id { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
