//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public double CGST { get; set; }
        public double SGST { get; set; }
        public Nullable<double> ServiceTax { get; set; }
        public int IndexId { get; set; }
    }
}
